# frontend/Dockerfile.dev
FROM node:20-alpine AS dev

WORKDIR /app

# Accept Stripe key as a build ARG
ARG NEXT_PUBLIC_CENTRAL_STRIPE_PUBLISHABLE_KEY
ENV NEXT_PUBLIC_CENTRAL_STRIPE_PUBLISHABLE_KEY=$NEXT_PUBLIC_CENTRAL_STRIPE_PUBLISHABLE_KEY

ARG NEXT_PUBLIC_USER_REDIRECT_BASE_URL
ENV NEXT_PUBLIC_USER_REDIRECT_BASE_URL=$NEXT_PUBLIC_USER_REDIRECT_BASE_URL

COPY package*.json ./
RUN npm install
COPY . .

ENV PORT=3000
EXPOSE ${PORT}

CMD ["npm", "run", "dev"]
